# Generated by Django 5.1.3 on 2024-12-02 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageExplorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='extra_images',
        ),
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.RemoveField(
            model_name='package',
            name='submitter',
        ),
        migrations.AddField(
            model_name='package',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='external_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(related_name='packages', to='packageExplorer.tag'),
        ),
        migrations.AlterField(
            model_name='package',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='packageExplorer.package')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
        migrations.AddField(
            model_name='package',
            name='extra_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
