# Generated by Django 5.1.3 on 2024-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageExplorer', '0002_remove_package_extra_images_remove_package_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stinky',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
