# Generated by Django 5.1.3 on 2024-12-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageExplorer', '0003_package_stinky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='extra_images',
        ),
        migrations.RemoveField(
            model_name='package',
            name='stinky',
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='packageExplorer.package')),
            ],
        ),
    ]
