# Generated by Django 5.1.3 on 2025-01-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packageExplorer', '0004_remove_package_extra_images_remove_package_stinky_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
